import {
  Check,
  ChevronsUpDown,
  Copy,
  CreditCard,
  DollarSign,
  Edit,
  ImagePlus,
  Loader,
  LucideIcon,
  Moon,
  MoreHorizontal,
  Package,
  Plus,
  PlusCircle,
  Search,
  Server,
  Store,
  Sun,
  Trash,
} from "lucide-react";

export type IconType = LucideIcon;

export const Icons = {
  loading: Loader,
  store: Store,
  chevronsArrow: ChevronsUpDown,
  check: Check,
  addCircle: PlusCircle,
  trash: Trash,
  server: Server,
  copy: Copy,
  plus: Plus,
  addImage: ImagePlus,
  search: Search,
  spread: MoreHorizontal,
  edit: Edit,
  creditCard: CreditCard,
  dolar: DollarSign,
  package: Package,
  lightMode: Sun,
  darkMode: Moon,
};
